# Set empty defaults
set(LIBDIRS    "" )
set(SRCDIRS    "" )
set(INCFILES   "" )
set(SRCFILES   "" )
set(EXEFILES   "" )
set(DATAFILES  "" )
set(PASSDIRS   "" )
set(DATASUBDIR "" )

# Add subdirectories that are roots to libraries
# eg. list(APPEND LIBDIRS "dir" )
# -- NONE FOR THIS DIR --

# Add directories that contribute source files 
# eg. list(APPEND SRCDIRS "dir" )
# -- NONE FOR THIS DIR --

# Add header files
# eg. list(APPEND INCFILES "file" )
list(APPEND INCFILES "gbpTrees_analysis.h" )

# Add source files
# eg. list(APPEND SRCFILES "file" )
list(APPEND SRCFILES "average_tree_branches.c" )
list(APPEND SRCFILES "init_precompute_treenode_markers.c" )
list(APPEND SRCFILES "free_precompute_treenode_markers.c" )
list(APPEND SRCFILES "precompute_treenode_markers.c" )
list(APPEND SRCFILES "precompute_treenode_markers_recursive.c" )
list(APPEND SRCFILES "precompute_treenode_markers_peak_mass_recursive.c" )
list(APPEND SRCFILES "fetch_treenode_precomputed_markers.c" )
list(APPEND SRCFILES "init_treenode_trend.c" )
list(APPEND SRCFILES "init_treenode_trend_coordinate.c" )
list(APPEND SRCFILES "init_treenode_trend_functions.c" )
list(APPEND SRCFILES "process_trees_by_snap.c" )
list(APPEND SRCFILES "compute_trees_analysis.c" )
list(APPEND SRCFILES "compute_trees_stats.c" )
list(APPEND SRCFILES "compute_trees_analysis_strayed_halos.c" )
list(APPEND SRCFILES "compute_trees_analysis_dropped_halos.c" )
list(APPEND SRCFILES "compute_trees_analysis_mergers.c" )
list(APPEND SRCFILES "compute_trees_analysis_emerged_halos.c" )
list(APPEND SRCFILES "compute_trees_analysis_fragmented_halos.c" )
list(APPEND SRCFILES "compute_treenode_list_marker_stats.c" )
list(APPEND SRCFILES "analyze_halos_and_N_subhalos.c" )
list(APPEND SRCFILES "init_treenode_hist.c" )
list(APPEND SRCFILES "add_to_treenode_hist.c" )
list(APPEND SRCFILES "write_treenode_hist.c" )
list(APPEND SRCFILES "write_treenode_list_hist.c" )
list(APPEND SRCFILES "write_treenode_all_hist.c" )
list(APPEND SRCFILES "move_treenode_to_snap.c" )
list(APPEND SRCFILES "free_treenode_hist.c" )
list(APPEND SRCFILES "init_treenode_list.c" )
list(APPEND SRCFILES "reset_treenode_list.c" )
list(APPEND SRCFILES "init_treenode_list_data.c" )
list(APPEND SRCFILES "finalize_treenode_list.c" )
list(APPEND SRCFILES "free_treenode_list.c" )
list(APPEND SRCFILES "add_to_treenode_list.c" )
list(APPEND SRCFILES "write_treenode_list_markers.c" )
list(APPEND SRCFILES "write_treenode_list_markers_header.c" )
list(APPEND SRCFILES "write_treenode_list_data.c" )
list(APPEND SRCFILES "write_treenode_list_data_header.c" )
list(APPEND SRCFILES "write_treenode_list_properties.c" )
list(APPEND SRCFILES "write_treenode_list_properties_header.c" )
list(APPEND SRCFILES "write_treenode_list_properties_set_ith.c" )
list(APPEND SRCFILES "write_tree_branches.c" )
list(APPEND SRCFILES "check_treenode_if_snap_equals_given.c" )
list(APPEND SRCFILES "check_treenode_if_main_progenitor.c" )
list(APPEND SRCFILES "check_treenode_if_merger.c" )
list(APPEND SRCFILES "check_treenode_if_central.c" )
list(APPEND SRCFILES "check_treenode_if_satellite.c" )
list(APPEND SRCFILES "check_treenode_if_group.c" )
list(APPEND SRCFILES "check_treenode_if_branch_start.c" )
list(APPEND SRCFILES "check_treenode_if_fragmented.c" )
list(APPEND SRCFILES "check_treenode_if_matched_to_emerged.c" )
list(APPEND SRCFILES "check_treenode_if_dropped.c" )
list(APPEND SRCFILES "fetch_trees_reference.c" )
list(APPEND SRCFILES "fetch_treenode_reference.c" )
list(APPEND SRCFILES "fetch_treenode_match_score.c" )
list(APPEND SRCFILES "fetch_treenode_delta_t.c" )
list(APPEND SRCFILES "fetch_treenode_delta_t_leaf.c" )
list(APPEND SRCFILES "fetch_treenode_delta_t_form.c" )
list(APPEND SRCFILES "fetch_treenode_properties.c" )
list(APPEND SRCFILES "fetch_treenode_backmatch.c" )
list(APPEND SRCFILES "fetch_treenode_backmatch_score.c" )
list(APPEND SRCFILES "fetch_treenode_backmatch_f_goodness.c" )
list(APPEND SRCFILES "fetch_treenode_progenitor_f_goodness.c" )
list(APPEND SRCFILES "fetch_treenode_descendant_f_goodness.c" )
list(APPEND SRCFILES "fetch_treenode_progenitor_score.c" )
list(APPEND SRCFILES "fetch_treenode_descendant_score.c" )
list(APPEND SRCFILES "fetch_treenode_M_vir.c" )
list(APPEND SRCFILES "fetch_treenode_R_vir.c" )
list(APPEND SRCFILES "fetch_treenode_sigmav.c" )
list(APPEND SRCFILES "fetch_treenode_c_NFW.c" )
list(APPEND SRCFILES "fetch_treenode_merger_info.c" )
list(APPEND SRCFILES "fetch_treenode_xi.c" )
list(APPEND SRCFILES "fetch_treenode_M_peak.c" )
list(APPEND SRCFILES "fetch_treenode_Vir_ratio.c" )
list(APPEND SRCFILES "fetch_treenode_x_off.c" )
list(APPEND SRCFILES "fetch_treenode_SSFctn.c" )
list(APPEND SRCFILES "fetch_treenode_list_local_log_sigma_vx.c" )
list(APPEND SRCFILES "fetch_treenode_tau_form.c" )
list(APPEND SRCFILES "fetch_treenode_tau_3to1.c" )
list(APPEND SRCFILES "fetch_treenode_tau_10to1.c" )
list(APPEND SRCFILES "fetch_treenode_x.c" )
list(APPEND SRCFILES "fetch_treenode_y.c" )
list(APPEND SRCFILES "fetch_treenode_z.c" )
list(APPEND SRCFILES "fetch_treenode_vx.c" )
list(APPEND SRCFILES "fetch_treenode_vy.c" )
list(APPEND SRCFILES "fetch_treenode_vz.c" )
list(APPEND SRCFILES "fetch_treenode_delta_r_MP.c" )
list(APPEND SRCFILES "fetch_treenode_n_particles.c" )
list(APPEND SRCFILES "fetch_treenode_n_particles_inclusive.c" )
list(APPEND SRCFILES "fetch_treenode_n_particles_peak.c" )
list(APPEND SRCFILES "fetch_treenode_n_particles_peak_inclusive.c" )
list(APPEND SRCFILES "fetch_treenode_n_particles_inclusive_peak.c" )
list(APPEND SRCFILES "fetch_treenode_substructure_rank.c" )
list(APPEND SRCFILES "fetch_treenode_z.c" )
list(APPEND SRCFILES "fetch_treenode_snapshot.c" )
list(APPEND SRCFILES "fetch_treenode_snap_tree.c" )
list(APPEND SRCFILES "fetch_treenode_halo_ID.c" )
list(APPEND SRCFILES "fetch_treenode_tree_case.c" )
list(APPEND SRCFILES "fetch_treenode_file_index.c" )
list(APPEND SRCFILES "fetch_treenode_progenitor_rank.c" )
list(APPEND SRCFILES "fetch_treenode_redshift.c" )
list(APPEND SRCFILES "set_treenode_hist_index.c" )
list(APPEND SRCFILES "write_treenode_markers.c" )
list(APPEND SRCFILES "read_treenode_markers.c" )
list(APPEND SRCFILES "find_treenode_snap_equals_given.c" )
list(APPEND SRCFILES "find_treenode_snap_equals_given_recursive.c" )
list(APPEND SRCFILES "find_treenode_main_progenitor.c" )
list(APPEND SRCFILES "find_treenode_last_snapshot.c" )
list(APPEND SRCFILES "find_treenode_branch_leaf.c" )
list(APPEND SRCFILES "find_treenode_M_peak.c" )
list(APPEND SRCFILES "find_treenode_formation.c" )
list(APPEND SRCFILES "find_treenode_last_merger.c" )
list(APPEND SRCFILES "find_treenode_accretion.c" )
list(APPEND SRCFILES "find_treesnap_snap.c" )
list(APPEND SRCFILES "find_treesnap_z.c" )

# Add executable source files (those with a main())
# eg. list(APPEND EXEFILES "file" )
# -- NONE FOR THIS DIR --

# Add data files
# eg. list(APPEND DATAFILES "file" )
# -- NONE FOR THIS DIR --

# Set data subdirectory
# eg. set(DATASUBDIR "dir" )

# Add subdirectories that we want to decend into
#   but which we won't scan for sources, etc
# eg. list(APPEND PASSDIRS "dir" )
# -- NONE FOR THIS DIR --

