# Build configuration parameters for project: gbpCode
- project_name: gbpCode
- project_author: Gregory B. Poole
- project_email: gbpoole@gmail.com
- project_description: One line description of project.
- kcov_token: unset
- gbpbuild_rel_path: .
