macro(project_init)
    set(_PROJECT_NAME "gbpCode")
endmacro()

macro(project_options)
    #========= Set project-specific options ========
    define_project_env_variable(USE_DOUBLE "Use double precision liberally"   OFF ON OFF)
    define_project_env_variable(SID_DEBUG  "Enable SID debugging information" OFF ON OFF)
    define_project_env_variable(USE_FFTW2  "Use v2 of FFTW"                   ON  ON OFF)
endmacro()

macro(project_dependencies)
    #=========== Add 3rd-party libraries ===========
    set_3rd_party_required("GSL")
    set_3rd_party_optional("MPI"     ON)
    set_3rd_party_optional("MPI_IO"  OFF)
    set_3rd_party_optional("GD"      ON)
    if(USE_FFTW2)
       set_3rd_party_optional("FFTW2" ON)
    else()
       set_3rd_party_optional("FFTW3" ON)
    endif()      
    set_3rd_party_optional("CUDA"    OFF)
    set_3rd_party_optional("CFITSIO" ON)
    set_3rd_party_optional("HDF5"    ON)    
    set_3rd_party_requested("GBP_DOCS_BUILD" ON)
endmacro()
